import Foundation

/// Turns one minute of raw Whisper output into clean prose, using the **local**
/// Ollama already running on this Mac.
///
/// ## Why not the Anthropic API, like the emotional paste it replaced
///
/// Because that path is dead and has been for a while: both keys in
/// `~/.training-assistants-secrets.env` answer *"Your credit balance is too low"*
/// (verified 2026-08-14), which is the same reason `summarize-on-break.sh` and
/// `flux-agent.sh` explicitly `env -u ANTHROPIC_API_KEY` before running claude.
/// The emotional paste never announced that it had stopped working, because a
/// shortcut whose whole output is "nothing happened" looks identical either way.
///
/// ## Why not `claude -p` on the subscription, like every other launcher here
///
/// Measured on this Mac: **~90 s** end to end for exactly this prompt (CLI
/// startup, auth, then the model). That is fine for the break-summary delta,
/// which nobody is waiting on, and unusable for a keypress — the whole feature
/// is "the sentence I just said, now".
///
/// ## So: local
///
/// `gemma3:4b` answers in ~4 s warm, ~15 s cold, costs nothing, works offline in
/// a venue with hostile Wi-Fi, and never sends a minute of a client's meeting to
/// a third party — which for a transcript of somebody else's room is the better
/// default anyway. Ollama runs as a brew LaunchAgent (`homebrew.mxcl.ollama`),
/// so it is up whenever the Mac is.
///
/// The model is asked for **one** thing — cleaned prose — and never for the
/// ladder of growing excerpts the picker shows. `TranscriptLadder` derives those
/// in Swift, which makes them monotone and guaranteed to end on the newest words
/// by construction rather than by the model's good behaviour, and cuts what has
/// to be generated by ~5× (the naive version re-emits the same minute five times
/// over, and the last rung is the slowest token of all).
enum TranscriptCleaner {
    /// `gemma3:4b` over `qwen2.5:7b`: on the same window qwen ignored the
    /// instruction and returned a third-person *summary* ("Victor spoke about…")
    /// in 27 s, where gemma returned the actual words in 15 s. A summary is the
    /// one output this feature must never produce — you are about to paste it as
    /// something you said.
    static let defaultModel = "gemma3:4b"
    private static let endpoint = URL(string: "http://localhost:11434/api/generate")!
    private static let timeout: TimeInterval = 60

    static var model: String {
        ProcessInfo.processInfo.environment["TRANSCRIPT_CLEANUP_MODEL"] ?? defaultModel
    }

    private static let systemPrompt = """
    You clean up raw speech-to-text output.

    The input is one minute of live Whisper transcript, one `[HH:MM] text` line \
    per transcribed audio chunk, oldest first. It contains filler words, false \
    starts, missing punctuation, and half-sentences repeated where two chunks \
    overlapped. There are no speaker labels — the microphones pick up everyone in \
    the room, so do NOT invent attributions or dialogue formatting.

    Rewrite it as clean, continuous prose:
    - drop filler words and false starts
    - fix punctuation and capitalization
    - merge the duplicated fragments that chunk overlap creates
    - keep the original language; do NOT translate
    - preserve the meaning and the speaker's own wording — this is cleanup, \
    NOT a summary, and NOT a paraphrase

    Output ONLY the cleaned text. No timestamps, no commentary, no bullet points, \
    no preamble.
    """

    enum CleanerError: LocalizedError {
        case unreachable(String)
        case http(Int, String)
        case emptyReply

        var errorDescription: String? {
            switch self {
            case .unreachable(let why):
                return "Ollama unreachable (\(why)) — is `homebrew.mxcl.ollama` running?"
            case .http(let code, let body):
                return "Ollama HTTP \(code): \(body.prefix(200))"
            case .emptyReply:
                return "Ollama returned nothing"
            }
        }
    }

    static func clean(_ transcript: String) async throws -> String {
        let body: [String: Any] = [
            "model": model,
            "system": systemPrompt,
            "prompt": transcript,
            "stream": false,
            // Low but not zero: this is a rewrite with one right answer, and
            // greedy decoding on a small model tends to loop on the repeated
            // fragments that chunk overlap leaves behind.
            "options": ["temperature": 0.2, "num_predict": 1200],
        ]

        var request = URLRequest(url: endpoint, timeoutInterval: timeout)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "content-type")
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let data: Data, response: URLResponse
        do {
            (data, response) = try await URLSession.shared.data(for: request)
        } catch {
            throw CleanerError.unreachable(error.localizedDescription)
        }

        if let http = response as? HTTPURLResponse, http.statusCode != 200 {
            throw CleanerError.http(http.statusCode, String(data: data, encoding: .utf8) ?? "(no body)")
        }
        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let reply = json["response"] as? String else {
            throw CleanerError.emptyReply
        }
        let cleaned = strip(reply)
        guard !cleaned.isEmpty else { throw CleanerError.emptyReply }
        return cleaned
    }

    /// Small models honour "output ONLY the cleaned text" *most* of the time and
    /// wrap the answer in a ``` fence or open with "Here is the cleaned text:"
    /// the rest of it. Both would end up on the clipboard verbatim, so both are
    /// taken off here rather than argued with in the prompt.
    static func strip(_ reply: String) -> String {
        var lines = reply.trimmingCharacters(in: .whitespacesAndNewlines)
            .components(separatedBy: "\n")

        if lines.first?.trimmingCharacters(in: .whitespaces).hasPrefix("```") == true {
            lines.removeFirst()
            if lines.last?.trimmingCharacters(in: .whitespaces).hasPrefix("```") == true {
                lines.removeLast()
            }
        }
        // A lead-in is a SHORT line ending in a colon. The length bound matters:
        // real speech ends a sentence with a colon often enough ("the rule is
        // this:"), and eating a genuine line of the transcript is worse than
        // leaving a stray preamble the eye can see in the picker.
        if let first = lines.first?.trimmingCharacters(in: .whitespaces),
           first.hasSuffix(":"), first.count <= 60, lines.count > 1 {
            lines.removeFirst()
        }
        return lines.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
